name: Bot Alert Saham
name: Bot Alert Saham

on:
  schedule:
    - cron: "0 * * * *"       # jalan tiap 1 jam (menit ke-00)
  workflow_dispatch: {}

permissions:
  contents: write             # boleh commit cache

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python bot/main.py

      - name: Commit cache (sent.json)
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/sent.json
            git commit -m "update cache [skip ci]"
            git push
          else
            echo "No cache changes."
          fi
