name: Bot Alert Saham
on:
  schedule:
    - cron: "*/10 * * * *"   # jalan tiap 10 menit
  workflow_dispatch: {}

permissions:
  contents: write

concurrency:
  group: news-bot
  cancel-in-progress: false

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          MAX_MSG_PER_CYCLE: "12"
        run: |
          python -V
          python bot/main.py

      - name: Commit cache (sent_items.json)
        run: |
          if [[ -n "$(git status --porcelain sent_items.json 2>/dev/null)" ]]; then
            git config user.name "news-bot"
            git config user.email "actions@github.com"
            git add sent_items.json
            git commit -m "chore: update sent_items.json"
            git push
          else
            echo "No cache changes."
          fi
